-- =============================================================================
-- Suncly - initial database schema
-- Migration: 0001_initial_schema.sql
-- Target:    Cloudflare D1 (SQLite)
--
-- What Suncly does: it fetches an A2A agent's Agent Card, tests whether the
-- agent really does what the card claims, and issues a signed attestation.
--
-- Reading order (same as the data flow):
--   1. organizations, users, organization_members, api_keys   -> who uses Suncly
--   2. agents, card_snapshots                                 -> what is tested
--   3. check_definitions                                      -> which tests exist
--   4. runs, check_results, http_exchanges                    -> what happened
--   5. signing_keys, attestations                             -> the signed result
--   6. audit_log                                              -> who did what
--
-- Conventions (SQLite has fewer types than Postgres, so these matter):
--   * IDs are UUID strings generated by the application (crypto.randomUUID()).
--     Exceptions: check_definitions (readable text id), audit_log (integer).
--   * Timestamps are TEXT in ISO 8601 UTC, e.g. 2026-10-03T18:50:54.615Z.
--     created_at fills itself in; updated_at must be set by the application.
--   * Booleans are INTEGER 0 or 1.
--   * JSON is stored as TEXT and validated with json_valid().
--   * Fixed value lists (status, role, outcome ...) are enforced with CHECK.
--   * Test data (snapshots, results, exchanges, attestations) is append-only:
--     rows are inserted, never edited. A new test = a new run.
--   * No BEGIN/COMMIT here: D1 applies each migration file atomically itself.
-- =============================================================================

-- =============================================================================
-- 1. WHO USES SUNCLY
-- =============================================================================

-- A customer team. Every agent and run belongs to exactly one organization.
CREATE TABLE organizations (
    id          TEXT PRIMARY KEY CHECK (length(id) = 36),
    name        TEXT NOT NULL CHECK (length(trim(name)) > 0),
    -- URL-safe unique name: lowercase letters, digits and hyphens (e.g. "acme-ai").
    slug        TEXT NOT NULL UNIQUE
                CHECK (length(slug) > 0
                   AND slug NOT GLOB '*[^a-z0-9-]*'
                   AND slug NOT GLOB '-*'
                   AND slug NOT GLOB '*-'
                   AND slug NOT GLOB '*--*'),
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
) STRICT;

-- A person who can log in. Passwords/sessions are handled by the auth
-- provider, not stored here.
CREATE TABLE users (
    id            TEXT PRIMARY KEY CHECK (length(id) = 36),
    email         TEXT NOT NULL CHECK (email LIKE '%_@_%'),
    display_name  TEXT,
    created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
) STRICT;

-- Email is unique regardless of letter case.
CREATE UNIQUE INDEX users_email_lower_key ON users (lower(email));

-- Which user belongs to which organization, and with what role.
CREATE TABLE organization_members (
    organization_id  TEXT NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    user_id          TEXT NOT NULL REFERENCES users (id)         ON DELETE CASCADE,
    role             TEXT NOT NULL DEFAULT 'member'
                     CHECK (role IN ('owner', 'admin', 'member')),
    created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY (organization_id, user_id)
) STRICT;

CREATE INDEX organization_members_user_id_idx ON organization_members (user_id);

-- Keys for calling the Suncly API from CI or scripts.
CREATE TABLE api_keys (
    id               TEXT PRIMARY KEY CHECK (length(id) = 36),
    organization_id  TEXT NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    name             TEXT NOT NULL CHECK (length(trim(name)) > 0),
    -- First characters of the key, shown in the UI so the user can recognise it.
    key_prefix       TEXT NOT NULL CHECK (length(key_prefix) BETWEEN 4 AND 16),
    -- SHA-256 (lowercase hex) of the full key. The key itself is NEVER stored.
    key_hash         TEXT NOT NULL UNIQUE
                     CHECK (length(key_hash) = 64 AND key_hash NOT GLOB '*[^0-9a-f]*'),
    created_by       TEXT REFERENCES users (id) ON DELETE SET NULL,
    created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    last_used_at     TEXT,
    revoked_at       TEXT
) STRICT;

CREATE INDEX api_keys_organization_id_idx ON api_keys (organization_id);

-- =============================================================================
-- 2. WHAT IS TESTED
-- =============================================================================

-- An A2A agent registered for testing. One row per agent per organization.
CREATE TABLE agents (
    id               TEXT PRIMARY KEY CHECK (length(id) = 36),
    organization_id  TEXT NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    name             TEXT NOT NULL CHECK (length(trim(name)) > 0),
    -- Full https URL of the Agent Card. Only https is allowed
    -- (SSRF protection starts here).
    card_url         TEXT NOT NULL CHECK (substr(card_url, 1, 8) = 'https://' AND length(card_url) > 8),
    created_by       TEXT REFERENCES users (id) ON DELETE SET NULL,
    created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (organization_id, card_url)
) STRICT;

-- An exact copy of an Agent Card at the moment it was fetched. Immutable.
-- A changed card = a new snapshot.
CREATE TABLE card_snapshots (
    id                 TEXT PRIMARY KEY CHECK (length(id) = 36),
    agent_id           TEXT NOT NULL REFERENCES agents (id) ON DELETE CASCADE,
    -- The Agent Card JSON exactly as the agent served it.
    raw_card           TEXT NOT NULL CHECK (json_valid(raw_card)),
    -- SHA-256 (lowercase hex) of the raw response bytes.
    -- This hash goes into the attestation.
    sha256             TEXT NOT NULL
                       CHECK (length(sha256) = 64 AND sha256 NOT GLOB '*[^0-9a-f]*'),
    -- A2A protocol version the card declares, if any.
    protocol_version   TEXT,
    -- 1 = the card passed JSON Schema validation for the A2A spec, 0 = it did not.
    is_schema_valid    INTEGER NOT NULL CHECK (is_schema_valid IN (0, 1)),
    -- JSON array of schema validation errors; empty array when valid.
    validation_errors  TEXT NOT NULL DEFAULT '[]'
                       CHECK (json_valid(validation_errors) AND json_type(validation_errors) = 'array'),
    fetched_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (agent_id, sha256),
    -- Lets runs reference (id, agent_id) so a run cannot point at another agent's card.
    UNIQUE (id, agent_id),
    -- A valid card has no validation errors.
    CHECK (is_schema_valid = 0 OR json_array_length(validation_errors) = 0)
) STRICT;

-- =============================================================================
-- 3. WHICH TESTS EXIST
-- =============================================================================

-- Catalog of all checks the test engine can run.
-- Rows are added by migrations, not by users.
CREATE TABLE check_definitions (
    -- Stable human-readable id, e.g. "capability.streaming".
    -- Never renamed once released.
    id           TEXT PRIMARY KEY
                 CHECK (id GLOB '[a-z]*.[a-z]*' AND id NOT GLOB '*[^a-z_.]*' AND id NOT GLOB '*..*' AND id NOT GLOB '*.'),
    category     TEXT NOT NULL
                 CHECK (category IN ('card', 'transport', 'capability', 'skill', 'error_handling', 'auth')),
    severity     TEXT NOT NULL CHECK (severity IN ('critical', 'major', 'minor')),
    title        TEXT NOT NULL,
    description  TEXT NOT NULL,
    -- 1 = the check runs once for every skill on the card; 0 = once per run.
    per_skill    INTEGER NOT NULL DEFAULT 0 CHECK (per_skill IN (0, 1)),
    is_active    INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
) STRICT;

INSERT INTO check_definitions (id, category, severity, title, description, per_skill) VALUES
    ('card.reachable',                 'card',           'critical', 'Agent Card is reachable',
     'The Agent Card URL answers over https with a successful status and JSON content.', 0),
    ('card.schema_valid',              'card',           'critical', 'Agent Card matches the A2A schema',
     'The Agent Card validates against the JSON Schema of the pinned A2A spec version.', 0),
    ('transport.endpoint_reachable',   'transport',      'critical', 'Declared endpoint answers',
     'The service URL declared on the card accepts a well-formed request.', 0),
    ('capability.streaming',           'capability',     'major',    'Streaming works as declared',
     'If the card declares streaming, a streaming request returns a valid event stream.', 0),
    ('capability.push_notifications',  'capability',     'major',    'Push notifications work as declared',
     'If the card declares push notifications, a notification config can be registered.', 0),
    ('skill.responds',                 'skill',          'major',    'Skill responds to its own example',
     'Sending one of the skill''s declared examples produces a completed task or a message.', 1),
    ('skill.output_modes',             'skill',          'major',    'Skill returns a declared output type',
     'The content type of the response is one of the output modes the card declares.', 1),
    ('error_handling.invalid_request', 'error_handling', 'minor',    'Malformed request is rejected correctly',
     'A malformed request returns a proper protocol error instead of a crash or a 200.', 0),
    ('error_handling.unknown_task',    'error_handling', 'minor',    'Unknown task id is rejected correctly',
     'Asking for a task id that does not exist returns the task-not-found error.', 0),
    ('auth.enforced',                  'auth',           'critical', 'Declared authentication is enforced',
     'If the card declares a security scheme, a request without credentials is rejected.', 0);

-- =============================================================================
-- 4. WHAT HAPPENED
-- =============================================================================

-- One execution of the test engine against one agent.
CREATE TABLE runs (
    id                TEXT PRIMARY KEY CHECK (length(id) = 36),
    agent_id          TEXT NOT NULL REFERENCES agents (id) ON DELETE CASCADE,
    -- The card version this run tested. NULL until the card is fetched
    -- (or if fetching failed).
    card_snapshot_id  TEXT,
    -- queued -> running -> completed | failed | cancelled.
    -- "failed" means Suncly itself broke, NOT that the agent failed checks.
    status            TEXT NOT NULL DEFAULT 'queued'
                      CHECK (status IN ('queued', 'running', 'completed', 'failed', 'cancelled')),
    -- A2A spec version the checks were run against.
    spec_version      TEXT NOT NULL,
    -- Version (git tag or commit) of the Suncly test engine.
    engine_version    TEXT NOT NULL,
    triggered_by      TEXT REFERENCES users (id) ON DELETE SET NULL,
    -- Why the run failed. Filled only when status = failed.
    error_message     TEXT,
    created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    started_at        TEXT,
    finished_at       TEXT,

    -- The snapshot must belong to the same agent as the run.
    FOREIGN KEY (card_snapshot_id, agent_id)
        REFERENCES card_snapshots (id, agent_id) ON DELETE CASCADE,

    -- Timestamps must agree with the status.
    CHECK (status <> 'queued'  OR (started_at IS NULL AND finished_at IS NULL)),
    CHECK (status <> 'running' OR (started_at IS NOT NULL AND finished_at IS NULL)),
    CHECK ((status IN ('completed', 'failed', 'cancelled')) = (finished_at IS NOT NULL)),
    CHECK (status NOT IN ('completed', 'failed') OR started_at IS NOT NULL),
    CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at),
    -- A completed run always has the card it tested; a failed run always says why.
    CHECK (status <> 'completed' OR card_snapshot_id IS NOT NULL),
    CHECK (status <> 'failed'    OR error_message IS NOT NULL)
) STRICT;

CREATE INDEX runs_agent_id_created_at_idx ON runs (agent_id, created_at DESC);
CREATE INDEX runs_card_snapshot_id_idx    ON runs (card_snapshot_id);
-- Lets the worker find the next job quickly.
CREATE INDEX runs_queued_idx ON runs (created_at) WHERE status = 'queued';

-- The outcome of one check in one run.
-- One row per check (and per skill for per-skill checks).
CREATE TABLE check_results (
    id                   TEXT PRIMARY KEY CHECK (length(id) = 36),
    run_id               TEXT NOT NULL REFERENCES runs (id) ON DELETE CASCADE,
    check_definition_id  TEXT NOT NULL REFERENCES check_definitions (id) ON DELETE RESTRICT,
    -- Skill id from the Agent Card for per-skill checks;
    -- empty string for run-level checks.
    skill_id             TEXT NOT NULL DEFAULT '',
    -- What the card claimed, in plain words, e.g. "capabilities.streaming = true".
    claim                TEXT NOT NULL,
    -- pass    = the claim is true
    -- fail    = the claim is false (the agent does not do what the card says)
    -- warn    = works, but deviates from the spec in a non-breaking way
    -- skipped = not applicable (e.g. the card does not claim streaming)
    -- error   = Suncly could not finish the check (timeout, network problem)
    outcome              TEXT NOT NULL
                         CHECK (outcome IN ('pass', 'fail', 'warn', 'skipped', 'error')),
    -- What Suncly observed. Required unless the outcome is pass.
    message              TEXT,
    duration_ms          INTEGER CHECK (duration_ms >= 0),
    created_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (run_id, check_definition_id, skill_id),
    -- Anything other than a pass must explain itself.
    CHECK (outcome = 'pass' OR message IS NOT NULL)
) STRICT;

CREATE INDEX check_results_check_definition_id_idx ON check_results (check_definition_id);

-- Evidence: the raw requests Suncly sent and the raw responses the agent returned.
CREATE TABLE http_exchanges (
    id                TEXT PRIMARY KEY CHECK (length(id) = 36),
    check_result_id   TEXT NOT NULL REFERENCES check_results (id) ON DELETE CASCADE,
    -- Order of the exchange within its check, starting at 1.
    seq               INTEGER NOT NULL CHECK (seq >= 1),
    request_method    TEXT NOT NULL
                      CHECK (request_method IN ('GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS')),
    request_url       TEXT NOT NULL,
    -- JSON object. Credentials (Authorization, API keys, cookies) MUST be
    -- redacted by the application before insert.
    request_headers   TEXT NOT NULL DEFAULT '{}'
                      CHECK (json_valid(request_headers) AND json_type(request_headers) = 'object'),
    request_body      TEXT,
    response_status   INTEGER CHECK (response_status BETWEEN 100 AND 599),
    -- JSON object, or NULL when no response arrived.
    response_headers  TEXT
                      CHECK (response_headers IS NULL
                          OR (json_valid(response_headers) AND json_type(response_headers) = 'object')),
    -- Plain text because it may be JSON, an SSE stream or an error page.
    -- Keep it small: the application truncates at its size limit.
    response_body     TEXT,
    -- 1 if the response body was cut at the size limit.
    body_truncated    INTEGER NOT NULL DEFAULT 0 CHECK (body_truncated IN (0, 1)),
    -- Network-level failure (timeout, DNS, TLS, blocked by SSRF guard)
    -- when no response arrived.
    error             TEXT,
    duration_ms       INTEGER CHECK (duration_ms >= 0),
    sent_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (check_result_id, seq),
    -- Every exchange ends in either a response or an error.
    CHECK (response_status IS NOT NULL OR error IS NOT NULL)
) STRICT;

-- =============================================================================
-- 5. THE SIGNED RESULT
-- =============================================================================

-- PUBLIC keys used to verify attestations. Private keys live in the secret
-- store (Workers secrets), NEVER in this database.
CREATE TABLE signing_keys (
    id          TEXT PRIMARY KEY CHECK (length(id) = 36),
    -- Short public identifier of the key, included in each attestation
    -- (e.g. "suncly-2026-10").
    key_id      TEXT NOT NULL UNIQUE,
    algorithm   TEXT NOT NULL DEFAULT 'ed25519' CHECK (algorithm = 'ed25519'),
    -- Base64-encoded Ed25519 public key.
    public_key  TEXT NOT NULL UNIQUE,
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    -- Set when the key stops signing new attestations.
    -- Old attestations stay verifiable.
    retired_at  TEXT
) STRICT;

-- The signed report for one completed run. At most one per run.
-- The application must only issue it for runs with status = completed.
CREATE TABLE attestations (
    id                 TEXT PRIMARY KEY CHECK (length(id) = 36),
    run_id             TEXT NOT NULL UNIQUE REFERENCES runs (id) ON DELETE CASCADE,
    signing_key_id     TEXT NOT NULL REFERENCES signing_keys (id) ON DELETE RESTRICT,
    -- Random unguessable id used in the public verification URL.
    public_id          TEXT NOT NULL UNIQUE
                       CHECK (length(public_id) BETWEEN 16 AND 64
                          AND public_id NOT GLOB '*[^A-Za-z0-9_-]*'),
    -- pass    = all checks passed
    -- partial = only minor checks failed
    -- fail    = a critical or major check failed
    verdict            TEXT NOT NULL CHECK (verdict IN ('pass', 'partial', 'fail')),
    -- JSON object: card hash, spec version, engine version, check outcomes, timestamps.
    payload            TEXT NOT NULL CHECK (json_valid(payload) AND json_type(payload) = 'object'),
    -- SHA-256 (lowercase hex) of the exact canonical bytes that were signed.
    payload_sha256     TEXT NOT NULL
                       CHECK (length(payload_sha256) = 64 AND payload_sha256 NOT GLOB '*[^0-9a-f]*'),
    -- Base64-encoded Ed25519 signature over the canonical payload bytes.
    signature          TEXT NOT NULL,
    issued_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    expires_at         TEXT,
    revoked_at         TEXT,
    revocation_reason  TEXT,
    CHECK (expires_at IS NULL OR expires_at > issued_at),
    CHECK ((revoked_at IS NULL) = (revocation_reason IS NULL))
) STRICT;

CREATE INDEX attestations_signing_key_id_idx ON attestations (signing_key_id);

-- =============================================================================
-- 6. WHO DID WHAT
-- =============================================================================

-- Append-only log of important actions.
-- Rows are never updated or deleted by the application.
CREATE TABLE audit_log (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id  TEXT REFERENCES organizations (id) ON DELETE SET NULL,
    -- NULL when the action was done by the system or an API key.
    actor_user_id    TEXT REFERENCES users (id) ON DELETE SET NULL,
    -- Dotted name, e.g. "agent.created", "run.started", "attestation.revoked".
    action           TEXT NOT NULL
                     CHECK (action GLOB '[a-z]*.[a-z]*' AND action NOT GLOB '*[^a-z_.]*' AND action NOT GLOB '*..*' AND action NOT GLOB '*.'),
    target_type      TEXT,
    target_id        TEXT,
    metadata         TEXT NOT NULL DEFAULT '{}'
                     CHECK (json_valid(metadata) AND json_type(metadata) = 'object'),
    created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    CHECK ((target_type IS NULL) = (target_id IS NULL))
) STRICT;

CREATE INDEX audit_log_organization_id_created_at_idx ON audit_log (organization_id, created_at DESC);

-- =============================================================================
-- VIEW: one line per run with counted outcomes (what the dashboard lists).
-- Computed live, so it can never disagree with check_results.
-- =============================================================================

CREATE VIEW run_summaries AS
SELECT
    r.id                AS run_id,
    r.agent_id          AS agent_id,
    a.organization_id   AS organization_id,
    r.status            AS status,
    r.created_at        AS created_at,
    r.started_at        AS started_at,
    r.finished_at       AS finished_at,
    COUNT(cr.id)                                   AS checks_total,
    COALESCE(SUM(cr.outcome = 'pass'), 0)          AS checks_passed,
    COALESCE(SUM(cr.outcome = 'fail'), 0)          AS checks_failed,
    COALESCE(SUM(cr.outcome = 'warn'), 0)          AS checks_warned,
    COALESCE(SUM(cr.outcome = 'skipped'), 0)       AS checks_skipped,
    COALESCE(SUM(cr.outcome = 'error'), 0)         AS checks_errored
FROM runs r
JOIN agents a              ON a.id = r.agent_id
LEFT JOIN check_results cr ON cr.run_id = r.id
GROUP BY r.id, r.agent_id, a.organization_id, r.status, r.created_at, r.started_at, r.finished_at;
